trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/NUnitTestProject1.csproj'
  
  - task: SpecFlowPlus@0
    inputs:
      generatorSource: 'TestAssembly'
      testAssemblyFilePath: 'NUnitTestProject1\**\NUnitTestProject1.dll'
      projectName: 'asd'